services:
  - type: web
    name: hidden-gems
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m web.app
    envVars:
      - key: FLASK_DEBUG
        value: false
      - key: PORT
        value: 10000
